dhakaMetro/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
     path('__debug__/', include('debug_toolbar.urls')),
    path('user/', include('auth_user.urls')),
    path('', include('product.urls')),
    path('user/', include('django.contrib.auth.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
        

product/urls.py
from django.urls import path
from .views import product_view, add_to_cart, order_view, invoicePDF
from django.contrib.auth.decorators import login_required
app_name = 'product'
urlpatterns = [
    path('', product_view.HomeView.as_view(), name='home'),
    path('product/<pk>/', product_view.ProductDetailView.as_view(), name='productDetailView'),
    path('product/', product_view.ProductListView.as_view(), name='productListView'),
    path('brandproduct/<pk>/', product_view.BrandListView.as_view(), name='brandListView'),
    path('categoryproduct/<pk>/', product_view.CategoryListView.as_view(), name='categoryListView'),
    path('subcategoryListView/<pk>/', product_view.SubCategoryListView.as_view(), name='subcategoryListView'),
    path('cart/', add_to_cart.cartView, name='cart'),
    path('checkout/', order_view.checkout, name='checkout'),
    path('success/', order_view.CheckoutSuccessView.as_view(), name='success'),
    path('cancel/', order_view.CheckoutFaildView.as_view(), name='Cancel'),
    path('fail_url/', order_view.CheckoutFaildView.as_view(), name='fail_url'),
    path('checkout/', order_view.checkout, name='checkout'),
    path('addCart/<pk>/', add_to_cart.cartCreateView, name='add_cart'),
    path('delete/<pk>/', login_required(add_to_cart.CartItemDelet.as_view()), name='cart_delete'),
    path('invoice/<str:html>/', invoicePDF.create_invioce_pdf, name='invoice'),
]

templates/cart/cart.html
{% extends "base.html" %}
{% load static %}


{% block contentBody %}
<!-- Begin Uren's Cart Area -->
<div class="uren-cart-area">
    <div class="container-fluid">
        {% if error_msg %}
        <div style="text-align: center;" class="alert alert-danger" role="alert">
            {{ error_msg }}
          </div>
        {% endif %}
        <div class="row">
            <div class="col-12">
                <!-- <form action="javascript:void(0)"> -->
                    <div class="table-content table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th class="uren-product-remove">remove</th>
                                    <th class="uren-product-thumbnail">images</th>
                                    <th class="cart-product-name">Product</th>
                                    <th class="uren-product-price">Unit Price</th>
                                    <th class="uren-product-quantity">Quantity</th>
                                    <th class="uren-product-subtotal">Total</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for cart_item in cart_items %}
                                <tr>
                                    <td class="uren-product-remove"><a href="{% url 'product:cart_delete' pk=cart_item.pk %}"><i
                                        class="fa fa-trash" title="Remove"></i></a></td>
                                        <td class="uren-product-thumbnail"><a
                                            href="{% url 'product:productDetailView' pk=cart_item.product.pk %}"><img
                                            src="{{ cart_item.product.image.url }}"
                                            alt="Uren's Cart Thumbnail"></a></td>
                                            <form method="POST">
                                            {% csrf_token %}
                                            <td class="uren-product-name">
                                                <a href="{% url 'product:productDetailView' pk=cart_item.product.pk %}">{{ cart_item.product.name }}</a>
                                                <br>
                                                <div class="product-size_box d-flex justify-content-center">
                                                <select class="myniceselect nice-select" name="variation">
                                                    {% for variation in cart_item.product.product_variation.all %}
                                                    {% if variation == cart_item.product_variant %}
                                                    <option value="{{ variation.id }}" selected>{{ variation.name }}
                                                    </option>
                                                    {% else %}
                                                    <option value="{{ variation.id }}">{{ variation.name }}</option>
                                                    {% endif %}
                                                    {% endfor %}
                                                </select>
                                            </div>
                                            <button type="submit" class="btn btn-secondary m-2">Update</button>
                                        </td>
                                        <td class="uren-product-price"><span class="amount">&#2547;
                                            {{ cart_item.product.offer_price }}</span>
                                            <input style="display: none;" type="number" name="cart-id" value="{{ cart_item.id }}">
                                        </td>
                                        <td class="quantity">
                                            <label>Quantity</label>
                                            <div class="cart-plus-minus">
                                                <input class="cart-plus-minus-box" name="quan" value="{{ cart_item.quantity }}"type="text">
                                                <div class="dec qtybutton">
                                                    <i class="fa fa-angle-down"></i>
                                                </div>
                                                <div class="inc qtybutton">
                                                    <i class="fa fa-angle-up"></i>
                                                </div>
                                            </div>
                                           
                                                <button type="submit" class="btn btn-secondary m-2">Update</button>
                                           
                                        </td>
                                    </form>
                                        <td class="product-subtotal"><span class="amount">&#2547;{{ cart_item.price }}</span>
                                        </td>
                                    </tr>

                                {% endfor %}
                            </tbody>
                        </table>
                    </div>

                    <div class="row">
                        <div class="col-md-5 ml-auto">
                            <div class="cart-page-total">
                                <h2>Cart totals</h2>
                                <ul>
                                    <li>Subtotal <span>&#2547;{{ subtotal }}</span></li>
                                    <li>Vat <span>&#2547;{{ vat }}</span></li>
                                    <li>Delivery Charge <span>&#2547;{{ delivery }}</span></li>
                                    <li>Total <span>&#2547;{{ total }}</span></li>
                                </ul>
                                <a href="{% url 'product:checkout' %}">Proceed to checkout</a>
                            </div>
                        </div>
                    </div>
                <!-- </form> -->
            </div>
        </div>
    </div>
</div>
<!-- Uren's Cart Area End Here -->

<script>
    let dec = document.getElementById('dec');
    console.log(dec);
    dec.addEventListener('click', upper)
    function upper(e) {
        console.log(e);
    }
</script>


{% endblock contentBody %}

templates/cart/checkout.html
{% extends "base.html" %}
{% load static %}


{% block contentBody %}
<!-- Begin Uren's Breadcrumb Area -->
<div class="breadcrumb-area">
    <div class="container">
        <div class="breadcrumb-content">

        </div>
    </div>
</div>
<!-- Uren's Breadcrumb Area End Here -->
<!-- Begin Uren's Checkout Area -->
<div class="checkout-area">
    <div class="container-fluid">
        <!-- <div class="row">
                    <div class="col-lg-12">
                        <div class="coupon-accordion">
                            <h3>Have a coupon? <span id="showcoupon">Click here to enter your code</span></h3>
                            <div id="checkout_coupon" class="coupon-checkout-content">
                                <div class="coupon-info">
                                    <form action="javascript:void(0)">
                                        <p class="checkout-coupon">
                                            <input placeholder="Coupon code" type="text">
                                            <input class="coupon-inner_btn" value="Apply Coupon" type="submit">
                                        </p>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div> -->
        <form method="POST">
            {% csrf_token %}
            <div class="row">
                <div class="col-lg-6 col-12">
                    <div class="checkbox-form">
                        <h3>Address Details</h3>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="checkout-form-list">
                                    <label>Full Name <span class="required">*</span></label>
                                    <input placeholder="Full Name" name="full_name" value="{{ address.name }}"
                                        type="text">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="checkout-form-list">
                                    <label>Phone Number <span class="required">*</span></label>
                                    <input placeholder="Phone Number" name="phone" value="{{ address.phone }}"
                                        type="text">
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="checkout-form-list">
                                    <label>Email</label>
                                    <input placeholder="Email" name="email" disabled value="{{ address.user.email }}"
                                        type="email">
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="checkout-form-list">
                                    <label>Address <span class="required">*</span></label>
                                    <input placeholder="Street address" name="address"
                                        value="{{ address.street_address }}" type="text">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="checkout-form-list">
                                    <label>Town / City <span class="required">*</span></label>
                                    <input placeholder="Town / City" name="city" value="{{ address.city }}" type="text">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="checkout-form-list">
                                    <label>Postcode / Zip <span class="required">*</span></label>
                                    <input placeholder="Postcode / Zip" name="zip" value="{{ address.zip_code }}"
                                        type="text">
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
                <div class="col-lg-6 col-12">
                    <div class="your-order">
                        <h3>Your order</h3>
                        <div class="your-order-table table-responsive">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th class="cart-product-name">Product</th>
                                        <th class="cart-product-total">Total</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for cart_item in cart_items %}
                                    <tr class="cart_item">
                                        <td class="cart-product-name">{{ cart_item.product.name }} ({{cart_item.product_variant.name}})<strong
                                                class="product-quantity">
                                                × {{ cart_item.quantity }}</strong></td>
                                        <td class="cart-product-total" style="text-align: right;"><span class="amount">&#2547; {{ cart_item.price }}</span></td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                                <tfoot>
                                    <tr class="cart-subtotal">
                                        <th>Cart Subtotal</th>
                                        <td style="text-align: right;"><span class="amount" >&#2547;{{ subtotal }}</span></td>
                                    </tr>
                                    <tr class="cart-subtotal">
                                        <th>Vat</th>
                                        <td style="text-align: right;"><span class="amount">&#2547;{{ vat }}</span></td>
                                    </tr>
                                    <tr class="cart-subtotal">
                                        <th>Delivary Charge</th>
                                        <td style="text-align: right;"><span class="amount">&#2547;{{ delivery }}</span></td>
                                    </tr>
                                    <tr class="order-total">
                                        <th>Order Total</th>
                                        <td style="text-align: right;"><strong><span class="amount">&#2547;{{ total }}</span></strong></td>
                                    </tr>
                                </tfoot>
                            </table>
                        </div>
                        <div class="payment-method">
                            <div class="card-header" id="#payment-3">
                                <div class="payment-accordion d-flex justify-content-center">
                                    <div id="accordion">
                                        <h5 class="panel-title">
                                            <a class="collapsed">
                                                Select Payment Method
                                            </a>
                                        </h5>
                                        <select class="myniceselect nice-select" name="payment_method">
                                            <!-- <option value="1" selected>SSLCOMMERZ</option> -->
                                            <option value="2" selected>Cash on Delivery</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="order-button-payment">
                                    <input value="Place order" type="submit">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
    </div>
</div>
</form>
<!-- Uren's Checkout Area End Here -->

{% endblock contentBody %}