dhakaMetro/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
     path('__debug__/', include('debug_toolbar.urls')),
    path('user/', include('auth_user.urls')),
    path('', include('product.urls')),
    path('user/', include('django.contrib.auth.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
        

product/urls.py
from django.urls import path
from .views import product_view, add_to_cart, order_view, invoicePDF
from django.contrib.auth.decorators import login_required
app_name = 'product'
urlpatterns = [
    path('', product_view.HomeView.as_view(), name='home'),
    path('product/<pk>/', product_view.ProductDetailView.as_view(), name='productDetailView'),
    path('product/', product_view.ProductListView.as_view(), name='productListView'),
    path('brandproduct/<pk>/', product_view.BrandListView.as_view(), name='brandListView'),
    path('categoryproduct/<pk>/', product_view.CategoryListView.as_view(), name='categoryListView'),
    path('subcategoryListView/<pk>/', product_view.SubCategoryListView.as_view(), name='subcategoryListView'),
    path('cart/', add_to_cart.cartView, name='cart'),
    path('checkout/', order_view.checkout, name='checkout'),
    path('success/', order_view.CheckoutSuccessView.as_view(), name='success'),
    path('cancel/', order_view.CheckoutFaildView.as_view(), name='Cancel'),
    path('fail_url/', order_view.CheckoutFaildView.as_view(), name='fail_url'),
    path('checkout/', order_view.checkout, name='checkout'),
    path('addCart/<pk>/', add_to_cart.cartCreateView, name='add_cart'),
    path('delete/<pk>/', login_required(add_to_cart.CartItemDelet.as_view()), name='cart_delete'),
    path('invoice/<str:html>/', invoicePDF.create_invioce_pdf, name='invoice'),
]

product/views/add_to_cart.py
from ..models.product_model import Product, ProductVariation, Category, Subcategory, Brand
from ..models.cart_models import Cart
from django.views.generic.edit import DeleteView
from django.urls import reverse
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.db.models import Sum
from datetime import datetime
import string
import random
# Create your views here.

@login_required
def cartView(request):
    if request.method == 'POST':
        cart = Cart.objects.get(id=request.POST['cart-id'])
        cart.product_variant = ProductVariation.objects.get(id=request.POST['variation']) 
        cart.quantity = request.POST['quan']
        cart.price = float(cart.product.offer_price * int(request.POST['quan']))
        cart.save()
    cart_items = Cart.objects.filter(user=request.user, checkoutstatus=False)
    total_items_price = cart_items.aggregate(Sum("price"))
    vat = 0
    subtotal = 0
    for cart_item in cart_items:
        vat += ((cart_item.price * cart_item.product.vat) / 100) 
        subtotal += cart_item.price 

    total = subtotal + vat + 120
    context = {
       'cart_items':cart_items,
       'vat':float("{:.2f}".format(vat)),
       'subtotal':subtotal,
       'total':float("{:.2f}".format(total)),
       'total_items_price':total_items_price,
       'delivery': 120
    }
    context['categorys'] = Category.objects.all().order_by('id')
    context['subcategorys'] = Subcategory.objects.all()
    context['brands'] = Brand.objects.all()
    context['products'] = Product.objects.all()
    return render(request, 'cart/cart.html', context=context)


def cartCreateView(request, pk):
    product = Product.objects.get(pk=pk)
    if request.user.is_authenticated:
        carts = Cart.objects.filter(user=request.user, checkoutstatus=False)
        cart = carts.first()
        user = request.user
        cart_item_in = False
        if cart:
            for cart in carts:
                try:
                    if cart.product.id == product.id and cart.product_variant.id == int(request.POST['size']):
                        if request.method == 'POST':
                            cart.quantity = cart.quantity + int(request.POST['quantity'])
                            cart.product_variant = ProductVariation.objects.get(id=request.POST['size'])
                            cart.price = (cart.price + (product.offer_price * int(request.POST['quantity'])))
                            cart.save()
                            return HttpResponseRedirect(reverse('product:cart'))
                except:
                    if cart.product == product and cart.product_variant.id == product.product_variation.all().first().id:
                        cart_item_in = cart
            if cart_item_in:
                cart_item_in.quantity = cart_item_in.quantity + 1
                cart_item_in.price = cart_item_in.price + cart_item_in.product.offer_price
                cart_item_in.save()
                return HttpResponseRedirect(reverse('product:cart'))
            order_id = cart.order_id
            
        else:
            now = str(datetime.now())
            p = ''.join(now.split(':'))
            w = ''.join(p.split('-'))
            w = ''.join(w.split('.'))
            tran_id = ''.join(w.split(' '))
            order_id = ''.join(random.choices(string.ascii_uppercase +
                                string.digits, k=4))
            order_id = order_id + tran_id[-5:]
        if request.method == 'POST':
            cook = request.POST['csrfmiddlewaretoken']
            Cart.objects.create(
                user=user, 
                product=product, 
                product_variant= ProductVariation.objects.get(id=request.POST['size']), 
                quantity= int(request.POST['quantity']),
                order_id=order_id, 
                price=(product.offer_price * int(request.POST['quantity']))
            )
        else:
            Cart.objects.create(
                user=user, 
                product=product, 
                product_variant=product.product_variation.all().first(), 
                order_id=order_id, 
                price=product.offer_price)
        return HttpResponseRedirect(reverse('product:cart'))
    else:
        cart = request.session.get('cart', {})
        cart['post'] = False
        if request.method == 'POST':
            cart['post'] = True
            cart['size'] = request.POST['size']
            cart['quantity'] = int(request.POST['quantity'])
        cart['prod_id'] = product.id
        request.session['cart'] = cart
        return HttpResponseRedirect(reverse('auth_user:login'))



class CartItemDelet(DeleteView):
    model = Cart
    success_url = reverse_lazy('product:cart')
    def get(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)

product/views/invoicePDF.py
from django.shortcuts import render, redirect
from auth_user.models import Address
from ..models.product_model import Category, Subcategory, Brand, Product
from ..models.cart_models import Cart, Order
from sslcommerz_lib import SSLCOMMERZ 
from django.http import HttpResponse 
from django.views.generic import View
from django.db.models import Sum
from datetime import datetime
from django.contrib import messages
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required



def create_invioce_pdf(request, html):
    print(html)
    return redirect('product:home')

product/views/order_view.py
from django.shortcuts import render, redirect
from auth_user.models import Address
from ..models.product_model import Category, Subcategory, Brand, Product
from ..models.cart_models import Cart, Order
from sslcommerz_lib import SSLCOMMERZ 
from django.http import HttpResponse 
from django.views.generic import View
from django.db.models import Sum
from datetime import datetime
from django.contrib import messages
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required



@login_required
def checkout(request):
    try:
        address = Address.objects.get(user=request.user, current_select=True)
    except:
        return redirect('auth_user:address_create')
    cart_items = Cart.objects.filter(user=request.user, checkoutstatus=False)
    total_items_price = cart_items.aggregate(Sum("price"))
    vat = 0
    subtotal = 0

    for cart_item in cart_items:
        vat += ((cart_item.price * cart_item.product.vat) / 100)
        subtotal += cart_item.price

    total = subtotal + vat + 120
    if request.method == 'POST':
        if address.billing_address == True:
            Address.objects.create(
                user = request.user,
                name = request.POST['full_name'],
                phone = request.POST['phone'],
                street_address = request.POST['address'],
                zip_code = request.POST['zip'],
                city = request.POST['city'],
                current_select = True
            )
            address.current_select = False
            address.save()
        else:
            address.name = request.POST['full_name']
            address.phone = request.POST['phone']
            address.street_address = request.POST['address']
            address.zip_code = request.POST['zip']
            address.city = request.POST['city']
            address.save()
        now = str(datetime.now())
        p = ''.join(now.split(':'))
        w = ''.join(p.split('-'))
        w = ''.join(w.split('.'))
        tran_id = ''.join(w.split(' '))
        if Order.objects.filter(order_id=cart_items[0].order_id).exists():
            order = Order.objects.get(order_id=cart_items[0].order_id)
        else:
            order = Order.objects.create(
                order_id = cart_items[0].order_id,
                address = address,
                user = request.user,
                total_amount = total,
                transaction_id = tran_id,
            )
        if request.POST['payment_method'] == '1':
            settings = { 'store_id': 'trade633426429cde9', 'store_pass': 'trade633426429cde9@ssl', 'issandbox': True }
            sslcz = SSLCOMMERZ(settings)
            post_body = {}
            post_body['total_amount'] = order.total_amount
            post_body['currency'] = "BDT"
            post_body['tran_id'] = order.transaction_id
            post_body['success_url'] = "http://127.0.0.1:8000/success/"
            post_body['fail_url'] = "http://127.0.0.1:8000/fail_url/"
            post_body['cancel_url'] = "http://127.0.0.1:8000/cancel/"
            post_body['emi_option'] = 0
            post_body['cus_name'] = order.address.name
            post_body['cus_email'] = address.user.email
            post_body['cus_phone'] = order.address.phone
            post_body['cus_add1'] = order.address.street_address
            post_body['cus_city'] = order.address.city
            post_body['cus_postcode'] = order.address.zip_code
            post_body['cus_country'] = "Bangladesh"
            post_body['shipping_method'] = "NO"
            post_body['multi_card_name'] = ""
            post_body['num_of_item'] = len(cart_items)
            post_body['product_name'] = order.order_id
            post_body['product_category'] = cart_items[0].product.subcategory.category.name
            post_body['product_profile'] = "general"
            response = sslcz.createSession(post_body) # API response
            return redirect(response["GatewayPageURL"])
        else:
            for cart_item in cart_items:
                cart_item.checkoutstatus = True
                cart_item.save()
            order.payment_method = 'COD'
            order.save()
            context = {
                'address': address,
                "title": "Checkout",
                'cart_items': [],
                'vat': 00.00,
                'subtotal': 00.00,
                'total': 00.00,
                'total_items_price': 00.00,
                'delivery': 120,
                'success': True
            }
            context['categorys'] = Category.objects.all().order_by('id')
            context['subcategorys'] = Subcategory.objects.all()
            context['brands'] = Brand.objects.all()
            context['products'] = Product.objects.all()
            return render(request, 'payment/success.html', context=context)
    context = {
        'address': address,
        "title": "Checkout",
        'cart_items': cart_items,
        'vat': float("{:.2f}".format(vat)),
        'subtotal': subtotal,
        'total': float("{:.2f}".format(total)),
        'total_items_price': total_items_price,
        'delivery': 120
    }
    context['categorys'] = Category.objects.all().order_by('id')
    context['subcategorys'] = Subcategory.objects.all()
    context['brands'] = Brand.objects.all()
    context['products'] = Product.objects.all()
    context['error_msg'] = "Sorry, Your cart is empty."
    if cart_items:
        return render(request, 'cart/checkout.html', context=context)
    else:
        return render(request, 'cart/cart.html', context=context)
       

@method_decorator(csrf_exempt, name='dispatch')
class CheckoutSuccessView(View):
    model = Order
    template_name = 'payment/fail_url.html'

    
    def get(self, request, *args, **kwargs):
        # return render(request, self.template_name,{'transaction':transaction})
        return HttpResponse('nothing to see')

    def post(self, request, *args, **kwargs):
        data = self.request.POST
        settings = { 'store_id': 'trade633426429cde9', 'store_pass': 'trade633426429cde9@ssl', 'issandbox': True }
        sslcz = SSLCOMMERZ(settings)
        post_body = data
        order = Order.objects.get(transaction_id=post_body['tran_id'])
        order.val_id = post_body['val_id']
        order.store_amount = post_body['store_amount']
        order.bank_tran_id = post_body['bank_tran_id']
        order.tran_date = post_body['tran_date']
        order.save()

        if sslcz.hash_validate_ipn(post_body):
            response = sslcz.validationTransactionOrder(post_body['val_id'])
            if response["status"] == "VALID":
                order.payment_status = "SU"
                print("payment", "%"*123)
            order.card_ref_id = response["card_ref_id"]
            order.payment_method = 'SSL'
            order.save()
            cart_items = Cart.objects.filter(user=order.user, checkoutstatus=False)
            for cart_item in cart_items:
                cart_item.checkoutstatus = True
                cart_item.save()
            messages.success(request,'Payment Successfull')
        else:
            messages.error(request,'Hash validation failed')
            print("Hash validation failed")
        context = {}
        context['categorys'] = Category.objects.all().order_by('id')
        context['subcategorys'] = Subcategory.objects.all()
        context['brands'] = Brand.objects.all()
        context['products'] = Product.objects.all()
        if self.request.user.is_authenticated:
            context['cart_items'] = Cart.objects.filter(user=self.request.user, checkoutstatus=False)
            context['total_items_price'] = context['cart_items'].aggregate(Sum("price"))
        return render(request, 'payment/success.html', context=context)

@method_decorator(csrf_exempt, name='dispatch')
class CheckoutFaildView(View):
    template_name = 'payment/fail_url.html'
    context = {}
    context['categorys'] = Category.objects.all().order_by('id')
    context['subcategorys'] = Subcategory.objects.all()
    context['brands'] = Brand.objects.all()
    context['products'] = Product.objects.all()
    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, context=self.context)
    def post(self, request, *args, **kwargs):
        data = self.request.POST
        return render(request, self.template_name, context=self.context)

templates/product/shop-grid-fullwidth.html
{% extends "base.html" %}
{% load static %}


{% block contentBody %}
<!-- Begin Uren's Shop Grid Fullwidth  Area -->
<div class="shop-content_wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <!-- <div class="shop-toolbar">
                    <div class="product-view-mode">
                        <a class="grid-1" data-target="gridview-1" data-toggle="tooltip" data-placement="top"
                            title="1">1</a>
                        <a class="grid-2" data-target="gridview-2" data-toggle="tooltip" data-placement="top"
                            title="2">2</a>
                        <a class="active grid-3" data-target="gridview-3" data-toggle="tooltip" data-placement="top"
                            title="3">3</a>
                        <a class="grid-4" data-target="gridview-4" data-toggle="tooltip" data-placement="top"
                            title="4">4</a>
                        <a class="grid-5" data-target="gridview-5" data-toggle="tooltip" data-placement="top"
                            title="5">5</a>
                    </div>
                </div> -->
                {% if  page_obj %}
                <div class="shop-product-wrap grid gridview-4 listfullwidth img-hover-effect_area row">
                    {% for product in page_obj  %}
                    <div class="col-lg-4">
                        <div class="product-slide_item">
                            <div class="inner-slide">
                                <div class="single-product">
                                    <div class="product-img">
                                        <a href="{% url 'product:productDetailView' pk=product.pk %}">
                                            <img class="primary-img" src="{{ product.image.url }}"
                                                alt="Uren's Product Image">
                                        </a>
                                        <div class="sticker">
                                            <span class="sticker">{{ product.product_tag.name }}</span>
                                        </div>
                                        <div class="add-actions">
                                            <ul>
                                                <li><a class="uren-add_cart" href="cart.html" data-toggle="tooltip"
                                                        data-placement="top" title="Add To Cart"><i
                                                            class="ion-bag"></i></a>
                                                </li>
                                                <!-- <li><a class="uren-wishlist" href="wishlist.html" data-toggle="tooltip"
                                                        data-placement="top" title="Add To Wishlist"><i
                                                            class="ion-android-favorite-outline"></i></a>
                                                </li> -->
                                            </ul>
                                        </div>
                                    </div>
                                    <div class="product-content">
                                        <div class="product-desc_info">
                                            <div class="rating-box">
                                                <ul>
                                                    <li><i class="ion-android-star"></i></li>
                                                    <li><i class="ion-android-star"></i></li>
                                                    <li><i class="ion-android-star"></i></li>
                                                    <li class="silver-color"><i class="ion-android-star"></i>
                                                    </li>
                                                    <li class="silver-color"><i class="ion-android-star"></i>
                                                    </li>
                                                </ul>
                                            </div>
                                            <h6><a class="product-name" href="{% url 'product:productDetailView' pk=product.pk %}">{{ product.name }}</a></h6>
                                            <div class="price-box">
                                                <span class="new-price">&#2547; {{ product.offer_price }}</span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                    
                </div>
           

                <div class="container d-flex justify-content-center">
                    <div class="col-lg-12">
                        <div class="uren-paginatoin-area">
                            <div class="row">
                                <div class="col-lg-12">
                                    <ul class="uren-pagination-box primary-color">
                                        {% if page_obj.has_previous %}
                                           <li><a class="Next" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
                                        {% endif %}
                                        <li><a href="javascript:void(0)" style="color: #FFC400;" disabled>Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</a></li>
                                        {% if page_obj.has_next %}
                                        <li><a class="Next" href="?page={{ page_obj.next_page_number }}">Next</a></li>
                                        {% endif %}
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                
            </div>
            {% else %}
            <div class="" style="text-align: center; padding-bottom: 30px;">
                <p>No product available.</p>
            </div>
            {% endif %}
        </div>
    </div>
</div>
<!-- Uren's Shop Grid Fullwidth  Area End Here -->



{% endblock contentBody %}

templates/product/shop-left-sidebar.html
{% extends "base.html" %}
{% load static %}


{% block contentBody %}
<div class="shop-content_wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-3 col-md-5 order-2 order-lg-1 order-md-1">
                <div class="uren-sidebar-catagories_area">
                    <div class="category-module uren-sidebar_categories">
                        <div class="category-module_heading">
                            <h5>Categories ({{ categorys.count }})</h5>
                        </div>
                        <div class="module-body">
                            <ul class="module-list_item">
                                <li>
                                    {% for category in categorys %}
                                    <a class="font-weight-bold" href="{% url 'product:categoryListView' pk=category.pk %}">{{ category.name }}<span></span></a>
                                    <ul class="module-sub-list_item">
                                        <li>
                                            {% for subcategory in subcategorys %}
                                                {% if subcategory.category == category %}
                                                    <a href="{% url 'product:subcategoryListView' pk=subcategory.pk %}">{{ subcategory.name }}<span></span></a>
                                                {% endif %}
                                            {% endfor %}
                                        </li>
                                    </ul>
                                    {% endfor %}

                                </li>
                                <li>
                                    <a class="font-weight-bold" href="javascript:void(0)">Brands</a>
                                    <ul class="module-sub-list_item">
                                        <li>
                                            {% for brand in brands %}
                                                <a href="{% url 'product:brandListView' pk=brand.pk %}">{{ brand.name }}<span></span></a>
                                            {% endfor %}
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
               
            </div>
            <div class="col-lg-9 col-md-7 order-1 order-lg-2 order-md-2">
                <!-- <div class="shop-toolbar">
                    <div class="product-view-mode">
                        <a class="grid-1" data-target="gridview-1" data-toggle="tooltip" data-placement="top"
                            title="1">1</a>
                        <a class="grid-2" data-target="gridview-2" data-toggle="tooltip" data-placement="top"
                            title="2">2</a>
                        <a class="active grid-3" data-target="gridview-3" data-toggle="tooltip" data-placement="top"
                            title="3">3</a>
                        <a class="grid-4" data-target="gridview-4" data-toggle="tooltip" data-placement="top"
                            title="4">4</a>
                        <a class="grid-5" data-target="gridview-5" data-toggle="tooltip" data-placement="top"
                            title="5">5</a>
                    </div>
                </div> -->
                {% if  page_obj %}
                <div class="shop-product-wrap grid gridview-4 listfullwidth img-hover-effect_area row">
                    {% for product in page_obj %}
                    <div class="col-lg-4">
                        <div class="product-slide_item">
                            <div class="inner-slide">
                                <div class="single-product">
                                    <div class="product-img">
                                        <a href="{% url 'product:productDetailView' pk=product.pk %}">
                                            <img class="primary-img" src="{{ product.image.url }}"
                                                alt="Uren's Product Image">
                                        </a>
                                        <div class="sticker">
                                            <span class="sticker">{{ product.product_tag.name }}</span>
                                        </div>
                                        <div class="add-actions">
                                            <ul>
                                                <li><a class="uren-add_cart" href="{% url 'product:add_cart' pk=product.pk %}" data-toggle="tooltip"
                                                        data-placement="top" title="Add To Cart"><i
                                                            class="ion-bag"></i></a>
                                                </li>
                                                <!-- <li><a class="uren-wishlist" href="wishlist.html" data-toggle="tooltip"
                                                        data-placement="top" title="Add To Wishlist"><i
                                                            class="ion-android-favorite-outline"></i></a>
                                                </li> -->
                                            </ul>
                                        </div>
                                    </div>
                                    <div class="product-content">
                                        <div class="product-desc_info">
                                            <div class="rating-box">
                                                <ul>
                                                    <li><i class="ion-android-star"></i></li>
                                                    <li><i class="ion-android-star"></i></li>
                                                    <li><i class="ion-android-star"></i></li>
                                                    <li class="silver-color"><i class="ion-android-star"></i>
                                                    </li>
                                                    <li class="silver-color"><i class="ion-android-star"></i>
                                                    </li>
                                                </ul>
                                            </div>
                                            <h6><a class="product-name"
                                                    href="{% url 'product:productDetailView' pk=product.pk %}">{{ product.name }}</a></h6>
                                            <div class="price-box">
                                                <span class="new-price">&#2547; {{ product.offer_price }}</span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                <div class="container d-flex justify-content-center">
                    <div class="col-lg-12">
                        <div class="uren-paginatoin-area">
                            <div class="row">
                                <div class="col-lg-12">
                                    <ul class="uren-pagination-box primary-color">
                                        {% if page_obj.has_previous %}
                                        <li><a class="Next"
                                                href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
                                        {% endif %}
                                        <li><a href="javascript:void(0)" style="color: #FFC400;" disabled>Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</a></li>
                                        {% if page_obj.has_next %}
                                        <li><a class="Next" href="?page={{ page_obj.next_page_number }}">Next</a></li>
                                        {% endif %}
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% else %}
            <div class="" style="text-align: center;">
                <p>No product available.</p>
            </div>
            {% endif %}

        </div>
    </div>
</div>

{% endblock contentBody %}