auth_user/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from django.contrib.auth.decorators import login_required
from django.contrib.auth import views as auth_views
from .views import user_views, footer_view

app_name = 'auth_user'

urlpatterns = [
    path('login/', user_views.LoginView.as_view(), name='login'),
    path('logout/', login_required(LogoutView.as_view(next_page='auth_user:login')), name='logout'),
    path('registration/', user_views.registrationView, name='registration'),
    path('profile/', login_required(user_views.ProfileView.as_view()), name='profile'),
    path('address-create/', user_views.address_create, name='address_create'),
    path('order-details/<str:order_id>', user_views.orderDetails, name='order-details'),
    path('generate-pdf/<str:order_id>', user_views.generate_pdf, name='generate_pdf'),


    path("password_reset/", user_views.PasswordResetOverridesView.as_view(template_name='accounts/password_reset.html', 
                                                                form_class=user_views.EmailValidationOnForgotPassword), name="password_reset"),
    path("password_reset/done/<email>/<countSender>/", user_views.PasswordResetDoneOverridesView.as_view(template_name="accounts/password_reset_done.html"), name="password_reset_done"),
    path("reset/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password_reset_confirm.html"), name="password_reset_confirm"),
    path("reset/done/", auth_views.PasswordResetCompleteView.as_view(template_name="accounts/reset_done.html"), name="password_reset_complete"),


    # footer views url
    path('about-us/', footer_view.AboutUs.as_view(), name='about_us'),
    path('contact-us/', footer_view.ContactUs.as_view(), name='contact_us'),
    path('frequently/', footer_view.Frequently.as_view(), name='frequently'),
    path('delivery-information/', footer_view.DeliveryInformation.as_view(), name='delivery_information'),
    path('privacy-policy/', footer_view.PrivacyPolicy.as_view(), name='privacy_policy'),
    path('returns/', footer_view.Returns.as_view(), name='returns'),
]

dhakaMetro/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
     path('__debug__/', include('debug_toolbar.urls')),
    path('user/', include('auth_user.urls')),
    path('', include('product.urls')),
    path('user/', include('django.contrib.auth.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
        

product/urls.py
from django.urls import path
from .views import product_view, add_to_cart, order_view, invoicePDF
from django.contrib.auth.decorators import login_required
app_name = 'product'
urlpatterns = [
    path('', product_view.HomeView.as_view(), name='home'),
    path('product/<pk>/', product_view.ProductDetailView.as_view(), name='productDetailView'),
    path('product/', product_view.ProductListView.as_view(), name='productListView'),
    path('brandproduct/<pk>/', product_view.BrandListView.as_view(), name='brandListView'),
    path('categoryproduct/<pk>/', product_view.CategoryListView.as_view(), name='categoryListView'),
    path('subcategoryListView/<pk>/', product_view.SubCategoryListView.as_view(), name='subcategoryListView'),
    path('cart/', add_to_cart.cartView, name='cart'),
    path('checkout/', order_view.checkout, name='checkout'),
    path('success/', order_view.CheckoutSuccessView.as_view(), name='success'),
    path('cancel/', order_view.CheckoutFaildView.as_view(), name='Cancel'),
    path('fail_url/', order_view.CheckoutFaildView.as_view(), name='fail_url'),
    path('checkout/', order_view.checkout, name='checkout'),
    path('addCart/<pk>/', add_to_cart.cartCreateView, name='add_cart'),
    path('delete/<pk>/', login_required(add_to_cart.CartItemDelet.as_view()), name='cart_delete'),
    path('invoice/<str:html>/', invoicePDF.create_invioce_pdf, name='invoice'),
]

auth_user/models.py
from django.db import models

# to create a Coustom user model and admin panel
from django.contrib.auth.models import AbstractUser
from .manager import UserManager

class User(AbstractUser):
    username = None
    first_name = None
    last_name = None
    full_name = models.CharField(max_length=255)
    email = models.EmailField(unique=True)
    phone = models.CharField(max_length=15, unique=True, null=True)
    image = models.ImageField(upload_to='user/', blank=True, null=True)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['full_name']
    object = UserManager()

    
    def __str__(self):
        return self.email
    
    def get_full_name(self):
        return self.full_name

    def get_short_name(self):
        return self.full_name


   

class Address(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    phone = models.CharField(max_length=15)
    street_address = models.CharField(max_length=255)
    zip_code = models.CharField(max_length=4, null=True)
    city = models.CharField(max_length=255)
    billing_address = models.BooleanField(default=False)
    current_select = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.user.full_name


class ContactMessage(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    subject = models.CharField(max_length=255)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.subject

auth_user/forms.py
from django import forms
from .models import User
from django.contrib.auth.forms import UserCreationForm  

class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('full_name', 'email','phone', 'password1', 'password2')

auth_user/views/footer_view.py
from django.shortcuts import render
from django.views.generic import TemplateView
from product.models.product_model import Category, Subcategory, Brand, Product
from ..models import ContactMessage


class AboutUs(TemplateView):
    template_name = 'footer/about_us.html'
    context = {}
    context['categorys'] = Category.objects.all().order_by('id')
    context['subcategorys'] = Subcategory.objects.all()
    context['brands'] = Brand.objects.all()
    context['products'] = Product.objects.all()

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, context=self.context)


class ContactUs(TemplateView):
    template_name = 'footer/contact.html'
    context = {}
    context['categorys'] = Category.objects.all().order_by('id')
    context['subcategorys'] = Subcategory.objects.all()
    context['brands'] = Brand.objects.all()
    context['products'] = Product.objects.all()

    def get(self, request, *args, **kwargs):
        self.context['message'] = False
        return render(request, self.template_name, context=self.context)
    def post(self, request):
        if request.method == 'POST':
            name = request.POST.get('con_name')
            email = request.POST.get('con_email')
            subject = request.POST.get('con_subject')
            message = request.POST.get('con_message')
            ContactMessage.objects.create(name=name, email=email, subject=subject, message=message)
            self.context['message'] = 'Successfully send your Message.'
            return render(request, self.template_name, context=self.context)
        return render(request, self.template_name, context=self.context)


class Frequently(TemplateView):
    template_name = 'footer/terms_conditions.html'
    context = {}
    context['categorys'] = Category.objects.all().order_by('id')
    context['subcategorys'] = Subcategory.objects.all()
    context['brands'] = Brand.objects.all()
    context['products'] = Product.objects.all()

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, context=self.context)


class DeliveryInformation(TemplateView):
    template_name = 'footer/delivery_information.html'
    context = {}
    context['categorys'] = Category.objects.all().order_by('id')
    context['subcategorys'] = Subcategory.objects.all()
    context['brands'] = Brand.objects.all()
    context['products'] = Product.objects.all()

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, context=self.context)


class PrivacyPolicy(TemplateView):
    template_name = 'footer/privacy_policy.html'
    context = {}
    context['categorys'] = Category.objects.all().order_by('id')
    context['subcategorys'] = Subcategory.objects.all()
    context['brands'] = Brand.objects.all()
    context['products'] = Product.objects.all()

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, context=self.context)


class Returns(TemplateView):
    template_name = 'footer/returns.html'
    context = {}
    context['categorys'] = Category.objects.all().order_by('id')
    context['subcategorys'] = Subcategory.objects.all()
    context['brands'] = Brand.objects.all()
    context['products'] = Product.objects.all()

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, context=self.context)

templates/auth_user/address.html
{% extends "base.html" %}
{% load static %}
{% block contentBody %}
<div class="checkout-area">
    <div class="container d-flex justify-content-center">
        <form method="POST">
            {% csrf_token %}
            <div class="row">
                <div class="col-12">
                    <div class="checkbox-form">
                        <h3 style="text-align: center;">Address Details</h3>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="checkout-form-list">
                                    <label>Full Name:<span class="required">*</span></label>
                                    <input placeholder="Full Name" name="full_name" value="{{ user.full_name }}" type="text">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="checkout-form-list">
                                    <label>Phone Number <span class="required">*</span></label>
                                    <input placeholder="Phone Number" name="phone" value="{{ user.phone }}" type="text">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="checkout-form-list">
                                    <label>Email <span class="required">*</span></label>
                                    <input disabled placeholder="Email" name="email" value="{{ user.email }}" type="email">
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="checkout-form-list">
                                    <label>Address <span class="required">*</span></label>
                                    <input placeholder="Street address" name="address" type="text">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="checkout-form-list">
                                    <label>Town / City <span class="required">*</span></label>
                                    <input placeholder="Town / City" name="city" type="text">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="checkout-form-list">
                                    <label>Postcode / Zip <span class="required">*</span></label>
                                    <input placeholder="Postcode / Zip" name="zip" type="text">
                                </div>
                            </div>
                        </div>
                        <div class="order-button-payment">
                            <input value="Add Address" type="submit">
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

{% endblock contentBody %}

templates/auth_user/login.html
{% extends "base.html" %}
{% load static %}
{% block contentBody %}
<div class="breadcrumb-area">
    <div class="container">
        <div class="breadcrumb-content">
           
        </div>
    </div>
</div>

<div class="uren-login-register_area">
    <div class="container-fluid">
        <div class="row d-flex justify-content-center">
            <div class="col-sm-12 col-md-12 col-xs-12 col-lg-6">
                <!-- Login Form s-->
                <form method="POST">
                    {% csrf_token %}
                    <div class="login-form">
                        <h4 class="login-title">Sign in</h4>
                        {% if message %}
                        <div style="text-align: center;" class="alert alert-danger" id="error" role="alert">
                            {{ message }} 
                        </div>
                       {% endif %}

                        <div class="row">
                            <div class="col-md-12 col-12">
                                <label>Email Address*</label>
                                <input type="email" placeholder="Email Address" name="email">
                            </div>
                            <div class="col-12 mb--20">
                                <label>Password*</label>
                                <input type="password" placeholder="Password" name="password">
                            </div>
                            <div class="col-md-4">
                                <div class="forgotton-password_info" >
                                    <a href="{% url 'auth_user:password_reset' %}">Forgot Password?</a> 
                                </div>
                            </div>
                            <div class="col-md-12">
                                <button class="uren-login_btn">Sign in</button>
                            </div>
                            <div class="col-md-12 pt-4" style="text-align: center;">
                                <div class="forgotton-password_info" >
                                   Don't have a account? <a href="{% url 'auth_user:registration' %}">Sign Up</a> 
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script>
    const myTimeout = setTimeout(myStopFunction, 10000);
    function myStopFunction() {
    document.getElementById('error').style.display = 'none';
    }
</script>
{% endblock contentBody %}

templates/auth_user/profile.html
{% extends "base.html" %}
{% load static %}
{% block contentBody %}
     <!-- Begin Uren's Breadcrumb Area -->
     <div class="breadcrumb-area">
        <div class="container">
            <div class="breadcrumb-content">
                
            </div>
        </div>
    </div>
    <!-- Uren's Breadcrumb Area End Here -->
    <!-- Begin Uren's Page Content Area -->
<main class="page-content">
    <!-- Begin Uren's Account Page Area -->
    <div class="account-page-area">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-3">
                    <ul class="nav myaccount-tab-trigger" id="account-page-tab" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link active" id="account-dashboard-tab" data-toggle="tab" href="#account-dashboard" role="tab" aria-controls="account-dashboard" aria-selected="true">Dashboard</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="account-orders-tab" data-toggle="tab" href="#account-orders" role="tab" aria-controls="account-orders" aria-selected="false">Orders</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="account-address-tab" data-toggle="tab" href="#account-address" role="tab" aria-controls="account-address" aria-selected="false">Addresses</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="account-details-tab" data-toggle="tab" href="#account-details" role="tab" aria-controls="account-details" aria-selected="false">Account Details</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="account-logout-tab" href="{% url 'auth_user:logout' %}" role="tab" aria-selected="false">Logout</a>
                        </li>
                    </ul>
                </div>
                <div class="col-lg-9">
                    <div class="tab-content myaccount-tab-content" id="account-page-tab-content">
                        <div class="tab-pane fade show active" id="account-dashboard" role="tabpanel" aria-labelledby="account-dashboard-tab">
                            <div class="myaccount-dashboard">
                                <p>Hello <b>{{ user.get_full_name }}</b></p>
                                <p>From your account dashboard you can view your recent orders and
                                    billing addresses.</p>
                            </div>
                        </div>
                        <div class="tab-pane fade" id="account-orders" role="tabpanel" aria-labelledby="account-orders-tab">
                            <div class="myaccount-orders">
                                <h4 class="small-title">MY ORDERS</h4>
                                <div class="table-responsive">
                                    <table class="table table-bordered table-hover">
                                        <tbody>
                                            <tr>
                                                <th>ORDER</th>
                                                <th>DATE</th>
                                                <th>STATUS</th>
                                                <th>TOTAL</th>
                                                <th></th>
                                            </tr>
                                            {% for order in orders %}
                                            <tr>
                                                <td><a class="account-order-id" href="javascript:void(0)">#{{ order.order_id }}</a></td>
                                                <td>{{ order.created_at|date:"M d, Y" }}</td>
                                                {% if order.delivery_status == 'CA' %}
                                                <td>Cancelled</td>
                                                {% elif order.delivery_status == 'PR' %}
                                                <td>Processing</td>
                                                {% else %}
                                                <td>Delivered</td>
                                                {% endif %}
                                                <td>{{ order.total_amount }}</td>
                                                <td><a href="{% url 'auth_user:order-details' order_id=order.order_id %}" class="uren-btn uren-btn_dark uren-btn_sm"><span>View</span></a>
                                                </td>
                                            </tr>
                                           {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                        <div class="tab-pane fade" id="account-address" role="tabpanel" aria-labelledby="account-address-tab">
                            <div class="myaccount-address">
                                <div class="row">
                                    <div class="col">
                                        <h4 class="small-title">BILLING ADDRESS</h4>
                                        <ul>
                                            <li>Name: <b>{{ billing_address.name }}</b></li>
                                            <li>Phone: <b>{{ billing_address.phone }}</b></li>
                                            <li>
                                                <address>
                                                    {{ billing_address.street_address }}
                                                </address>
                                            </li>
                                            <li>ZIP code: <b>{{ billing_address.zip_code }}</b></li>
                                            <li>City: <b>{{ billing_address.city }}</b></li>
                                        </ul>
                                    </div>
                                    <div class="col">
                                        <h4 class="small-title">SHIPPING ADDRESS</h4>
                                        <ul>
                                            <li>Name: <b>{{ current_address.name }}</b></li>
                                            <li>Phone: <b>{{ current_address.phone }}</b></li>
                                            <li>
                                                <address>
                                                    {{ current_address.street_address }}
                                                </address>
                                            </li>
                                            <li>ZIP code: <b>{{ current_address.zip_code }}</b></li>
                                            <li>City: <b>{{ current_address.city }}</b></li>
                                        </ul>
                                        <!-- <div class="pt-2">
                                            <a class="btn btn-secondary" href="#account-details" role="button">Change Address</a>
                                        </div> -->
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="tab-pane fade" id="account-details" role="tabpanel" aria-labelledby="account-details-tab">
                            <div class="myaccount-details">
                                <form action="#" class="uren-form">
                                    <div class="uren-form-inner">
                                        <div class="single-input single-input-half">
                                            <label for="account-details-firstname">Full Name*</label>
                                            <input type="text" disabled value="{{ user.get_full_name }}"  name="full_name" placeholder="Full Name" id="account-details-firstname">
                                        </div>
                                        <div class="single-input single-input-half">
                                            <label for="account-details-lastname">Phone Number*</label>
                                            <input type="tel" disabled value="{{ user.phone }}" id="account-details-lastname" name="phone"  placeholder="Phone Number">
                                        </div>
                                        <div class="single-input">
                                            <label for="account-details-email">Email*</label>
                                            <input type="email" disabled value="{{ user.email }}" id="account-details-email" name="email" placeholder="Email">
                                        </div>
                                        <!-- <div class="single-input">
                                            <label for="account-details-oldpass">Current Password(leave blank to leave
                                                unchanged)</label>
                                            <input type="password" id="account-details-oldpass" name="current_pass" placeholder="Current Password">
                                        </div>
                                        <div class="single-input">
                                            <label for="account-details-newpass">New Password (leave blank to leave
                                                unchanged)</label>
                                            <input type="password" id="account-details-newpass" name="new_password" placeholder="New Password">
                                        </div>
                                        <div class="single-input">
                                            <label for="account-details-confpass">Confirm New Password</label>
                                            <input type="password" id="account-details-confpass" name="confirm_password" placeholder="Confirm New Password">
                                        </div>
                                        <div class="single-input">
                                            <button class="uren-btn uren-btn_dark" type="submit"><span>SAVE
                                            CHANGES</span></button>
                                        </div> -->
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Uren's Account Page Area End Here -->
</main>
{% endblock contentBody %}

templates/auth_user/registration.html
{% extends "base.html" %}
{% load static %}
{% block contentBody %}
<div class="breadcrumb-area">
    <div class="container">
        <div class="breadcrumb-content">
           
        </div>
    </div>
</div>

<div class="uren-login-register_area">
    <div class="container-fluid">
        <div class="row d-flex justify-content-center">
            <div class="col-sm-12 col-md-12 col-lg-6 col-xs-12">
                <form method="POST">
                    {% csrf_token %}
                    <div class="login-form">
                        <h4 class="login-title">Sign up</h4>
                        {% if message %}
                        <div style="text-align: center;" id="error"  class="alert alert-danger" role="alert">
                            {{ message }}
                        </div>
                        {% endif %}
                        <div class="row">
                            <div class="col-md-12">
                                <label>Full Name*</label>
                                <input type="text" placeholder="First Name" maxlength="255" required id="id_full_name" name="full_name">
                            </div>
                            <div class="col-md-12">
                                <label>Email Address*</label>
                                <input type="email" placeholder="email" name="email" maxlength="254" autofocus required id="id_email">
                            </div>
                          
                            <div class="col-md-12">
                                <label>Phone Number*</label>
                                <input type="text" name="phone" maxlength="15" required id="id_phone" placeholder="Phone Number">
                            </div>
                          
                            <div class="col-md-6">
                                <label>Password*</label>
                                <input type="password" name="password1" autocomplete="new-password" required id="id_password1">
                            </div>
                            <div class="col-md-6">
                                <label>Confirm Password*</label>
                                <input type="password" name="password2" autocomplete="new-password" onkeyup='check();' required id="id_password2">
                                <span id='message'></span>
                            </div>
                            <div class="col-12">
                                <button class="uren-register_btn" id="register" disabled>Sing up</button>
                            </div>
                            <div class="col-md-12 pt-4" style="text-align: center;">
                                <div class="forgotton-password_info" >
                                   Already have a account? <a href="{% url 'auth_user:login' %}">Sign up</a> 
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script>

    var check = function() {
    if (document.getElementById('id_password1').value === document.getElementById('id_password2').value) {
        document.getElementById('message').style.color = 'green';
        document.getElementById('message').innerHTML = 'Matching';
        document.getElementById('register').style.background = '#ffc400';
        document.getElementById('register').removeAttribute('disabled');
    } else {
        document.getElementById('message').style.color = 'red';
        document.getElementById('message').innerHTML = 'Not matching';
    }
    }


    const myTimeout = setTimeout(myStopFunction, 10000);
    function myStopFunction() {
    document.getElementById('error').style.display = 'none';
    }
</script>
{% endblock contentBody %}