dhakaMetro/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
     path('__debug__/', include('debug_toolbar.urls')),
    path('user/', include('auth_user.urls')),
    path('', include('product.urls')),
    path('user/', include('django.contrib.auth.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
        

product/urls.py
from django.urls import path
from .views import product_view, add_to_cart, order_view, invoicePDF
from django.contrib.auth.decorators import login_required
app_name = 'product'
urlpatterns = [
    path('', product_view.HomeView.as_view(), name='home'),
    path('product/<pk>/', product_view.ProductDetailView.as_view(), name='productDetailView'),
    path('product/', product_view.ProductListView.as_view(), name='productListView'),
    path('brandproduct/<pk>/', product_view.BrandListView.as_view(), name='brandListView'),
    path('categoryproduct/<pk>/', product_view.CategoryListView.as_view(), name='categoryListView'),
    path('subcategoryListView/<pk>/', product_view.SubCategoryListView.as_view(), name='subcategoryListView'),
    path('cart/', add_to_cart.cartView, name='cart'),
    path('checkout/', order_view.checkout, name='checkout'),
    path('success/', order_view.CheckoutSuccessView.as_view(), name='success'),
    path('cancel/', order_view.CheckoutFaildView.as_view(), name='Cancel'),
    path('fail_url/', order_view.CheckoutFaildView.as_view(), name='fail_url'),
    path('checkout/', order_view.checkout, name='checkout'),
    path('addCart/<pk>/', add_to_cart.cartCreateView, name='add_cart'),
    path('delete/<pk>/', login_required(add_to_cart.CartItemDelet.as_view()), name='cart_delete'),
    path('invoice/<str:html>/', invoicePDF.create_invioce_pdf, name='invoice'),
]

templates/payment/cancel.html
{% extends "base.html" %}
{% load static %}


{% block contentBody %}
        <!-- Begin Uren's Breadcrumb Area -->
        <div class="breadcrumb-area">
            <div class="container">
                
            </div>
        </div>
        <!-- Uren's Breadcrumb Area End Here -->
        <!-- Begin Uren's Error 404 Page Area -->
        <div class="error404-area">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-8 ml-auto mr-auto text-center">
                        <div class="search-error-wrapper">
                            <h1>404</h1>
                            <h2>Cancel payment</h2>
                            <p class="short_desc">Please contact us?</p>
                            <div class="uren-btn-ps_center"></div>
                            <a href="{% url 'product:home' %}" class="uren-error_btn">Back To Home Page</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Uren's Error 404 Page End Here -->
{% endblock contentBody %}

templates/payment/fail_url.html
{% extends "base.html" %}
{% load static %}


{% block contentBody %}
        <!-- Begin Uren's Breadcrumb Area -->
        <div class="breadcrumb-area">
            <div class="container">
                <div class="breadcrumb-content">
                    
                </div>
            </div>
        </div>
        <!-- Uren's Breadcrumb Area End Here -->
        <!-- Begin Uren's Error 404 Page Area -->
        <div class="error404-area">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-8 ml-auto mr-auto text-center">
                        <div class="search-error-wrapper">
                            <h1>404</h1>
                            <h2>Transaction Failed </h2>
                            <p class="short_desc">Please contact us?</p>
                            <div class="uren-btn-ps_center"></div>
                            <a href="{% url 'product:home' %}" class="uren-error_btn">Back To Home Page</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Uren's Error 404 Page End Here -->
{% endblock contentBody %}

templates/payment/success.html
{% extends "base.html" %}
{% load static %}


{% block contentBody %}
        <!-- Begin Uren's Breadcrumb Area -->
        <div class="breadcrumb-area">
            <div class="container">
                <div class="breadcrumb-content">
                    
                </div>
            </div>
        </div>
        <!-- Uren's Breadcrumb Area End Here -->
        <!-- Begin Uren's Error 404 Page Area -->
        <div class="error404-area">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-8 ml-auto mr-auto text-center">
                        <div class="search-error-wrapper">
                            <h1>200</h1>
                            {% if success %}
                            <h2>Order Successful</h2>
                            <p class="short_desc">Hey, {{ user.get_full_name }}! Thank you for purchasing!</p>
                            <div class="uren-btn-ps_center"></div>
                            {% else %}
                            <h2>Payment Successful</h2>
                            <p class="short_desc">Hey, {{ user.get_full_name }}! Thank you for purchasing! Your payment has been confirmed.</p>
                            <div class="uren-btn-ps_center"></div>
                            {% endif %}
                            <br>
                            <a href="{% url 'product:home' %}" class="uren-error_btn">Back To Home Page</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Uren's Error 404 Page End Here -->
{% endblock contentBody %}